### ISSUE TITLE
VIM Format C# Cleanup and Code Samples

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-format#41]
# TODO

- [x] Remove unused Geometry/ classes:
  - [x] ArrayOps.tt + ArrayOps.cs
  - [x] Geometry/Topology.cs
  - [x] Geometry/Serialization.cs
  - [x] ...Classes which are only used within the Vim.Format.Core assembly (in the scope of the vimaec/platform.sln) i.e. self-dependencies
  
- [x] Absorb C# parts of the `sroberge/vimx_stable` branch (ask Simon for any clarifications)
  - [x] 1. Refactored BFast
  - [x] 2. G3dNext (to replace existing G3d)
  - [x] 3. Removal of LinqArray where possible

- [ ] New VIM API to open/load VIM files (VimModel.cs)
  - Attempt to replace all usages of VimScene with VimModel

- [ ] Add ElementInfo_v2.cs which uses an EntityTableSet instead of a DocumentModel to perform its queries

- [ ] Code samples/tests + documentation
